create table customer(
    id            int generated by default as identity primary key,
    full_name     varchar(200) not null,
    year_of_birth int check(year_of_birth > 1950)  not null,
    phone_number  int not null,
    email         varchar(200) not null
);


create table storage(
    id          int generated by default as identity primary key,
    customer_id int references customer(id) on delete set null,
    row         varchar not null,
    number      int not null,
    size        int not null,
    taken_at    timestamp
);



create table person(
    id       int generated by default as identity primary key,
    username varchar(100) not null,
    password varchar      not null,
    role     varchar(100) not null
);

insert into person(username, password, role) values ('admin', 12345,'ADMIN');
